gui:
  nerdFontsVersion: "3"
  border: rounded
  showRandomTip: false
  theme:
    activeBorderColor: ['#F6E72B', bold]
    inactiveBorderColor: ['#45335F']
    searchingActiveBorderColor: ['#8A62C5', bold]
    optionsTextColor: ['#8A62C5']
    selectedLineBgColor: ['#251938']
    cherryPickedCommitBgColor: ['#322543']
    cherryPickedCommitFgColor: ['#E8E6EA']
    unstagedChangesColor: ['#FF6670']
    defaultFgColor: ['#E8E6EA']
  authorColors:
    '*': '#A99BAC'
