gui:
  nerdFontsVersion: "3"
  border: rounded
  showRandomTip: false
  theme:
    activeBorderColor: ['#F6E72B', bold]
    inactiveBorderColor: ['#6D115F']
    searchingActiveBorderColor: ['#D72AC0', bold]
    optionsTextColor: ['#D72AC0']
    selectedLineBgColor: ['#28083E']
    cherryPickedCommitBgColor: ['#3B104F']
    cherryPickedCommitFgColor: ['#E8E6EA']
    unstagedChangesColor: ['#FF6670']
    defaultFgColor: ['#E8E6EA']
  authorColors:
    '*': '#A99BAC'
